--- # MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/localhost:3306/jonsoft?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: root
    password: dnseo4904!

--- # Server
server:
  port: 8080

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates # classpath:/templates
    suffix: .html

--- #
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database: mysql